[package]
name = "ZKML"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = "1.0.0"
cosmwasm-schema = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8"
bincode = "1.3"

[dependencies.bellman]
version = "0.10.0"
features = ["main"]
